task:
  only_if: $CIRRUS_TAG == ''
  timeout_in: 120m
  matrix:
    - name: linux-amd64
      compute_engine_instance:
        image_project: cirrus-images
        image: family/docker-builder
        platform: linux
        cpu: 8
        memory: 8G

    - name: linux-arm64
      compute_engine_instance:
        image_project: cirrus-images
        image: family/docker-builder-arm64
        architecture: arm64
        platform: linux
        cpu: 4
        memory: 4G

  build_script: make build
  run_script: make test

task:
  only_if: $CIRRUS_TAG != ''
  alias: build-linux-image
  timeout_in: 120m
  env:
    DOCKER_USERNAME: ENCRYPTED[db65fd6fc1af68040964a27c82f2cbd202c849199038cfddc961a573d803a4f2793ba30eede0b6bcdb6bbf29f5c4f012]
    DOCKER_PASSWORD: ENCRYPTED[a1503baddfbe37c5a4474c46ec12b11beee3d16c054c1fa5bfcdde674be32524781f9d4e4d9444db6575fc5aa6270040]
  matrix:
    - name: linux-amd64
      env:
        CIRRUS_ARCH: amd64
      compute_engine_instance:
        image_project: cirrus-images
        image: family/docker-builder
        platform: linux
        cpu: 8
        memory: 8G

    - name: linux-arm64
      env:
        CIRRUS_ARCH: arm64
      compute_engine_instance:
        image_project: cirrus-images
        image: family/docker-builder-arm64
        architecture: arm64
        platform: linux
        cpu: 4
        memory: 4G

  build_script: TAG=$CIRRUS_ARCH make build
  login_script: docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
  push_script: docker push joseluisq/rust-linux-darwin-builder:$CIRRUS_ARCH

release_docker_builder:
  only_if: $CIRRUS_TAG != ''
  depends_on:
    - build-linux-image
  env:
    DOCKER_USERNAME: ENCRYPTED[db65fd6fc1af68040964a27c82f2cbd202c849199038cfddc961a573d803a4f2793ba30eede0b6bcdb6bbf29f5c4f012]
    DOCKER_PASSWORD: ENCRYPTED[a1503baddfbe37c5a4474c46ec12b11beee3d16c054c1fa5bfcdde674be32524781f9d4e4d9444db6575fc5aa6270040]
  login_script: |
    docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
  push_latest_script: |
    docker manifest create \
      joseluisq/rust-linux-darwin-builder:latest \
        --amend joseluisq/rust-linux-darwin-builder:amd64 \
        --amend joseluisq/rust-linux-darwin-builder:arm64
    docker manifest push joseluisq/rust-linux-darwin-builder:latest
  pull_latest_script: |
    docker pull joseluisq/rust-linux-darwin-builder:amd64
    docker pull joseluisq/rust-linux-darwin-builder:arm64
  push_aliases_script: |
    SEMVER=${CIRRUS_TAG##*v}
    SEMVER_MAJOR=${SEMVER%.*.*}
    SEMVER_MINOR=${SEMVER%.*}

    docker manifest create \
      joseluisq/rust-linux-darwin-builder:${SEMVER} \
        --amend joseluisq/rust-linux-darwin-builder:amd64 \
        --amend joseluisq/rust-linux-darwin-builder:arm64
    docker manifest push joseluisq/rust-linux-darwin-builder:${SEMVER}

    docker manifest create \
      joseluisq/rust-linux-darwin-builder:${SEMVER_MAJOR} \
        --amend joseluisq/rust-linux-darwin-builder:amd64 \
        --amend joseluisq/rust-linux-darwin-builder:arm64
    docker manifest push joseluisq/rust-linux-darwin-builder:${SEMVER_MAJOR}

    docker manifest create \
      joseluisq/rust-linux-darwin-builder:${SEMVER_MINOR} \
        --amend joseluisq/rust-linux-darwin-builder:amd64 \
        --amend joseluisq/rust-linux-darwin-builder:arm64
    docker manifest push joseluisq/rust-linux-darwin-builder:${SEMVER_MINOR}
